[package]
name = "staurox-client"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-client = "0.30.1"
anchor-lang = "0.30.1"
solana-sdk = "1.18"
solana-client = "1.18"
anyhow = "1.0"
shellexpand = "3.1"
bs58 = "0.5"